# Generated by Django 4.2 on 2023-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="students",
            field=models.ManyToManyField(related_name="schools", to="school.student"),
        ),
    ]
